#!/bin/sh
OLDPATH="$PATH"
REALPATH="`realpath $0`"
WHEREAMI="`dirname $REALPATH`"
export PATH="$WHEREAMI/node_binaries/bin:$PATH"

if [ -z "$1" ]; then
  echo ""
  echo "Welcome to Typesetter. A command line tool to typeset graphic design for printing."
  echo "Type:  typesetter help  ...to find out how to use this tool."
  echo ""
  exit 0
else
 INFILE="`realpath $1`"
fi

if [ "$1" = "help" ]; then
  echo ""
  echo "To create a typeset PDF, please specify an image file as input for the design."
  echo "If a corresponding typeset JSON file exists, it will be used to format the output."
  echo "Example: typesetter mysticker.png"
  echo ""
  echo "To make your own typeset file, look at typeset_example.json for an example."
  echo ""
  exit 0
fi

cd "$WHEREAMI"

TMPLDEFAULT="default"

if [ -z "$2" ]; then TEMPLATE="$TMPLDEFAULT"; else TEMPLATE="$2"; fi

echo "Saving typeset output to $1.pdf (using template '$TEMPLATE')"
node typesetter.js -i "$INFILE" -t $TEMPLATE > __tmp.html && wkhtmltopdf -s A4 -B 0 -L 0 -R 0 -T 0 __tmp.html "$INFILE.pdf"
rm __tmp.html > /dev/null
# TEST: node typesetter.js -i "$INFILE" -t $TEMPLATE

cd - > /dev/null
PATH="$OLDPATH"
